login_attempt= "User Attempted to login with credentials\nUsername: {0}\nPassword: {1}"
login_success= "User {0} logged in successfully"
login_fail= "User Failed to login with credentials\nUsername: {0}\nPassword: {1} {2}"
scrapping_user="Started scrapping for {0}'s {1} at: {2}"
mass_user="Started scrapping for {0} of all Users at: {1}"
import_users="Found {0} users at: {1}"