# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand2Usersinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'brand2usersinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=99, null=True)),
                ('userid', models.BigIntegerField(blank=True, db_column='userID', null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'followers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Followers2Usersinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'followers2usersinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hashtagbrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, max_length=99, null=True)),
            ],
            options={
                'db_table': 'hashtagBrands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hashtagstyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, max_length=99, null=True)),
                ('firstviewtimestamp', models.DateTimeField(db_column='firstviewTimestamp')),
            ],
            options={
                'db_table': 'hashtagStyle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.CharField(db_column='postID', max_length=200, unique=True)),
                ('post_timestamp', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=99, null=True)),
                ('comments_count', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('comment_likes_count', models.IntegerField(blank=True, null=True)),
                ('postpicture', models.TextField(blank=True, db_column='postPicture', null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Style2Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'style2hashtag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=99, null=True)),
                ('description', models.CharField(blank=True, max_length=99, null=True)),
            ],
            options={
                'db_table': 'styles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('likes_count', models.IntegerField(blank=True, null=True)),
                ('comments_count', models.IntegerField(blank=True, null=True)),
                ('followed_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeseries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=99, null=True, unique=True)),
                ('items', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lists',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'output',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threadid', models.BigIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=99, null=True)),
                ('input', models.TextField(blank=True, null=True)),
                ('stop', models.DateTimeField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Useraccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(max_length=99, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('profilepicture', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('cookie', models.TextField(blank=True, null=True)),
                ('deviceid', models.CharField(max_length=99, null=True)),
                ('uuid', models.CharField(max_length=199, null=True)),
                ('advertisingid', models.CharField(max_length=199, null=True)),
                ('phoneid', models.CharField(max_length=199, null=True)),
                ('accountid', models.CharField(max_length=99, null=True)),
            ],
            options={
                'db_table': 'useraccounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usersinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=99, unique=True)),
                ('userid', models.BigIntegerField(db_column='userID', unique=True)),
                ('fullname', models.CharField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('isprivate', models.IntegerField(blank=True, db_column='isPrivate', null=True)),
                ('followed_by', models.BigIntegerField(blank=True, null=True)),
                ('follows', models.IntegerField(blank=True, null=True)),
                ('profilepicture', models.TextField(blank=True, db_column='profilePicture', null=True)),
                ('geo_media_count', models.IntegerField(blank=True, null=True)),
                ('media_count', models.IntegerField(blank=True, null=True)),
                ('usertags_count', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.IntegerField(blank=True, null=True)),
                ('is_business', models.IntegerField(blank=True, null=True)),
                ('comments_count', models.IntegerField(blank=True, null=True)),
                ('likes_count', models.IntegerField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'usersinfo',
                'managed': True,
            },
        ),
    ]
