# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
